 #!/bin/bash
 
dist_path=../dist/pc/snopf/
 
rm -rf ${dist_path}libQt5WebEngineCore.so.5
rm -rf ${dist_path}libQt53DRender.so.5
rm -rf ${dist_path}libcrypto.so.1.1
rm -rf ${dist_path}libQt5Charts.so.5
rm -rf ${dist_path}libQt5Bluetooth.so.5
rm -rf ${dist_path}libQt5Multimedia.so.5
rm -rf ${dist_path}libQt5Quick3DRuntimeRender.so.5
rm -rf ${dist_path}libQt5Pdf.so
rm -rf ${dist_path}libasound.so.2
rm -rf ${dist_path}libQt5XmlPatterns.so.5
rm -rf ${dist_path}libQt5Quick.so.5
rm -rf ${dist_path}libQt5QuickTemplates2.so.5
rm -rf ${dist_path}libQt5WaylandCompositor.so.5
rm -rf ${dist_path}libQt5VirtualKeyboard.so.5
rm -rf ${dist_path}libQt5DataVisualization.so.5
rm -rf ${dist_path}libQt5WaylandClient.so.5
rm -rf ${dist_path}libnss3.so
rm -rf ${dist_path}libcairo.so.2
rm -rf ${dist_path}libasound.so.2
rm -rf ${dist_path}libQt53DExtras.so.5
rm -rf ${dist_path}libgdk-3.so.0
rm -rf ${dist_path}libQt5EglFSDeviceIntegration.so.5
rm -rf ${dist_path}libQt5Quick3D.so.5
rm -rf ${dist_path}libQt5Positioning.so.5
rm -rf ${dist_path}libQt5RemoteObjects.so.5
rm -rf ${dist_path}libQt5QuickParticles.so.5
rm -rf ${dist_path}libQt5Quick3DRender.so.5
rm -rf ${dist_path}libQt53DAnimation.so.5
rm -rf ${dist_path}libQt53DCore.so.5
rm -rf ${dist_path}libvorbisenc.so.2
rm -rf ${dist_path}libQt53DInput.so.5
rm -rf ${dist_path}libQt5WebEngine.so.5
rm -rf ${dist_path}libQt5Scxml.so.5
rm -rf ${dist_path}libQt5Sql.so.5
rm -rf ${dist_path}libQt5Test.so.5
rm -rf ${dist_path}libQt5Nfc.so.5
rm -rf ${dist_path}libQt5Scxml.so.5
rm -rf ${dist_path}libpulsecommon-11.1.so
rm -rf ${dist_path}libsndfile.so.1
rm -rf ${dist_path}libFLAC.so.8
rm -rf ${dist_path}libssl.so.1.1
rm -rf ${dist_path}libQt5Bodymovin.so.5
rm -rf ${dist_path}libQt5QuickShapes.so.5
rm -rf ${dist_path}libQt5Sensors.so.5
rm -rf ${dist_path}libpulse.so.0
rm -rf ${dist_path}libQt5QuickControls2.so.5
rm -rf ${dist_path}libQt5Quick3DAssetImport.so.5
rm -rf ${dist_path}libQt5WebChannel.so.5
rm -rf ${dist_path}libQt5MultimediaQuick.so.5
rm -rf ${dist_path}libQt5PositioningQuick.so.5
rm -rf ${dist_path}libvorbis.so.0
rm -rf ${dist_path}libQt5Gamepad.so.5
rm -rf ${dist_path}libQt5QuickTest.so.5
rm -rf ${dist_path}libQt53DQuickScene2D.so.5
rm -rf ${dist_path}PySide2/QtQml.abi3.so
rm -rf ${dist_path}PySide2/qml

