# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_request_dialog.ui',
# licensing of 'password_request_dialog.ui' applies.
#
# Created: Wed Jan 22 13:54:54 2020
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_PasswordRequestDialog(object):
    def setupUi(self, PasswordRequestDialog):
        PasswordRequestDialog.setObjectName("PasswordRequestDialog")
        PasswordRequestDialog.resize(314, 241)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PasswordRequestDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(PasswordRequestDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pinEdit = QtWidgets.QLineEdit(PasswordRequestDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinEdit.sizePolicy().hasHeightForWidth())
        self.pinEdit.setSizePolicy(sizePolicy)
        self.pinEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.pinEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pinEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.pinEdit.setInputMask("")
        self.pinEdit.setText("")
        self.pinEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pinEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.pinEdit.setObjectName("pinEdit")
        self.horizontalLayout_6.addWidget(self.pinEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.hostnameComboBox = QtWidgets.QComboBox(PasswordRequestDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostnameComboBox.sizePolicy().hasHeightForWidth())
        self.hostnameComboBox.setSizePolicy(sizePolicy)
        self.hostnameComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.hostnameComboBox.setEditable(True)
        self.hostnameComboBox.setCurrentText("")
        self.hostnameComboBox.setObjectName("hostnameComboBox")
        self.verticalLayout.addWidget(self.hostnameComboBox)
        self.accountComboBox = QtWidgets.QComboBox(PasswordRequestDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountComboBox.sizePolicy().hasHeightForWidth())
        self.accountComboBox.setSizePolicy(sizePolicy)
        self.accountComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.accountComboBox.setEditable(True)
        self.accountComboBox.setCurrentText("")
        self.accountComboBox.setObjectName("accountComboBox")
        self.verticalLayout.addWidget(self.accountComboBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(PasswordRequestDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(PasswordRequestDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.passwordSettingsButton = QtWidgets.QPushButton(PasswordRequestDialog)
        self.passwordSettingsButton.setObjectName("passwordSettingsButton")
        self.horizontalLayout.addWidget(self.passwordSettingsButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.infoLabel = QtWidgets.QLabel(PasswordRequestDialog)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(PasswordRequestDialog)
        QtCore.QMetaObject.connectSlotsByName(PasswordRequestDialog)

    def retranslateUi(self, PasswordRequestDialog):
        PasswordRequestDialog.setWindowTitle(QtWidgets.QApplication.translate("PasswordRequestDialog", "Snopf Password Request", None, -1))
        self.pinEdit.setPlaceholderText(QtWidgets.QApplication.translate("PasswordRequestDialog", "Pin", None, -1))
        self.passwordSettingsButton.setText(QtWidgets.QApplication.translate("PasswordRequestDialog", "Password Settings", None, -1))
        self.infoLabel.setText(QtWidgets.QApplication.translate("PasswordRequestDialog", "TextLabel", None, -1))

import resources_rc
